name: Update CHANGELOG PR NUMBER
permissions:
  contents: write
  pull-requests: write
on:
  pull_request_review:
    # types: [submitted]
jobs:
  update-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Required for checkout and push
    steps:
      # - name: Fail if not approved
      #   if: github.event.review.state != 'approved'
      #   run: exit 1
      - name: Checkout PR branch
      # if: github.event.review.state == 'approved'
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          fetch-depth: 0

      - name: Update PR number in CHANGELOG
        shell: bash
        run: |
          sed -i '/^##/,$ {s/#pr/#${{ github.event.pull_request.number }}/g}' ./CHANGELOG.md
          if [ $(git status --porcelain | wc -l) -eq 0 ]; then
            echo "No changes to commit."
            exit 0
          fi

          # Configure Git
          git config user.name "RChangelog[bot]"
          git config user.email "155627257+RChangelog[bot]@users.noreply.github.com"

          # Commit and push changes
          git add CHANGELOG.md
          git commit --amend --no-edit
          git push -f